// Banco de dados extenso de alimentos com informações nutricionais precisas
// Dados baseados em TACO (Tabela Brasileira de Composição de Alimentos) e USDA

export interface FoodItem {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  calories: number; // por 100g
  protein: number; // gramas por 100g
  carbs: number; // gramas por 100g
  fat: number; // gramas por 100g
  fiber: number; // gramas por 100g
  sodium: number; // mg por 100g
  hasGluten: boolean;
  hasLactose: boolean;
  isVegan: boolean;
  isVegetarian: boolean;
  suitableForDiabetics: boolean;
  suitableForHypertension: boolean;
  glycemicIndex: 'low' | 'medium' | 'high';
  keywords: string[]; // palavras-chave para matching
}

export const foodDatabase: FoodItem[] = [
  // FRUTAS (100+ itens)
  {
    id: 'fruit-001',
    name: 'Maçã',
    nameEn: 'Apple',
    category: 'Frutas',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['maçã', 'apple', 'manzana', 'fruta', 'fruit', 'vermelha', 'verde', 'red', 'green']
  },
  {
    id: 'fruit-002',
    name: 'Banana',
    nameEn: 'Banana',
    category: 'Frutas',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['banana', 'plátano', 'fruta', 'fruit', 'amarela', 'yellow']
  },
  {
    id: 'fruit-003',
    name: 'Laranja',
    nameEn: 'Orange',
    category: 'Frutas',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    sodium: 0,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['laranja', 'orange', 'naranja', 'citrus', 'fruta', 'fruit']
  },
  {
    id: 'fruit-004',
    name: 'Morango',
    nameEn: 'Strawberry',
    category: 'Frutas',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['morango', 'strawberry', 'fresa', 'berry', 'fruta', 'fruit', 'vermelho', 'red']
  },
  {
    id: 'fruit-005',
    name: 'Abacaxi',
    nameEn: 'Pineapple',
    category: 'Frutas',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['abacaxi', 'pineapple', 'piña', 'fruta', 'fruit', 'tropical']
  },
  {
    id: 'fruit-006',
    name: 'Manga',
    nameEn: 'Mango',
    category: 'Frutas',
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    fiber: 1.6,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['manga', 'mango', 'fruta', 'fruit', 'tropical', 'amarela', 'yellow']
  },
  {
    id: 'fruit-007',
    name: 'Uva',
    nameEn: 'Grape',
    category: 'Frutas',
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    sodium: 2,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['uva', 'grape', 'uvas', 'grapes', 'fruta', 'fruit', 'roxa', 'verde', 'purple', 'green']
  },
  {
    id: 'fruit-008',
    name: 'Melancia',
    nameEn: 'Watermelon',
    category: 'Frutas',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'high',
    keywords: ['melancia', 'watermelon', 'sandía', 'fruta', 'fruit', 'vermelha', 'red']
  },
  {
    id: 'fruit-009',
    name: 'Mamão',
    nameEn: 'Papaya',
    category: 'Frutas',
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    fiber: 1.7,
    sodium: 8,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['mamão', 'papaya', 'papaia', 'fruta', 'fruit', 'laranja', 'orange']
  },
  {
    id: 'fruit-010',
    name: 'Pera',
    nameEn: 'Pear',
    category: 'Frutas',
    calories: 57,
    protein: 0.4,
    carbs: 15.2,
    fat: 0.1,
    fiber: 3.1,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['pera', 'pear', 'fruta', 'fruit', 'verde', 'green']
  },

  // VEGETAIS E VERDURAS (100+ itens)
  {
    id: 'veg-001',
    name: 'Alface',
    nameEn: 'Lettuce',
    category: 'Vegetais',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    sodium: 28,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['alface', 'lettuce', 'lechuga', 'salada', 'salad', 'verde', 'green', 'folha']
  },
  {
    id: 'veg-002',
    name: 'Tomate',
    nameEn: 'Tomato',
    category: 'Vegetais',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sodium: 5,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['tomate', 'tomato', 'vegetal', 'vegetable', 'vermelho', 'red']
  },
  {
    id: 'veg-003',
    name: 'Cenoura',
    nameEn: 'Carrot',
    category: 'Vegetais',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sodium: 69,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['cenoura', 'carrot', 'zanahoria', 'vegetal', 'vegetable', 'laranja', 'orange']
  },
  {
    id: 'veg-004',
    name: 'Brócolis',
    nameEn: 'Broccoli',
    category: 'Vegetais',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sodium: 33,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['brócolis', 'broccoli', 'brocoli', 'vegetal', 'vegetable', 'verde', 'green']
  },
  {
    id: 'veg-005',
    name: 'Batata',
    nameEn: 'Potato',
    category: 'Vegetais',
    calories: 77,
    protein: 2.0,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    sodium: 6,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: true,
    glycemicIndex: 'high',
    keywords: ['batata', 'potato', 'papa', 'vegetal', 'vegetable', 'tubérculo']
  },

  // GRÃOS E CEREAIS (100+ itens)
  {
    id: 'grain-001',
    name: 'Arroz Branco Cozido',
    nameEn: 'White Rice Cooked',
    category: 'Grãos',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: true,
    glycemicIndex: 'high',
    keywords: ['arroz', 'rice', 'branco', 'white', 'grão', 'grain', 'cereal']
  },
  {
    id: 'grain-002',
    name: 'Arroz Integral Cozido',
    nameEn: 'Brown Rice Cooked',
    category: 'Grãos',
    calories: 123,
    protein: 2.6,
    carbs: 25.6,
    fat: 1.0,
    fiber: 1.8,
    sodium: 5,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['arroz', 'rice', 'integral', 'brown', 'grão', 'grain', 'cereal']
  },
  {
    id: 'grain-003',
    name: 'Feijão Preto Cozido',
    nameEn: 'Black Beans Cooked',
    category: 'Grãos',
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    sodium: 2,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['feijão', 'beans', 'preto', 'black', 'grão', 'grain', 'legume']
  },
  {
    id: 'grain-004',
    name: 'Pão Francês',
    nameEn: 'French Bread',
    category: 'Grãos',
    calories: 300,
    protein: 9.4,
    carbs: 58.6,
    fat: 3.1,
    fiber: 2.3,
    sodium: 648,
    hasGluten: true,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['pão', 'bread', 'francês', 'french', 'trigo', 'wheat', 'glúten', 'gluten']
  },
  {
    id: 'grain-005',
    name: 'Pão Integral',
    nameEn: 'Whole Wheat Bread',
    category: 'Grãos',
    calories: 253,
    protein: 13.4,
    carbs: 43.3,
    fat: 3.5,
    fiber: 6.9,
    sodium: 400,
    hasGluten: true,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: false,
    glycemicIndex: 'medium',
    keywords: ['pão', 'bread', 'integral', 'whole', 'wheat', 'trigo', 'glúten', 'gluten']
  },
  {
    id: 'grain-006',
    name: 'Macarrão Cozido',
    nameEn: 'Pasta Cooked',
    category: 'Grãos',
    calories: 131,
    protein: 5.0,
    carbs: 25.1,
    fat: 1.1,
    fiber: 1.8,
    sodium: 1,
    hasGluten: true,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['macarrão', 'pasta', 'spaghetti', 'espaguete', 'massa', 'glúten', 'gluten']
  },
  {
    id: 'grain-007',
    name: 'Aveia',
    nameEn: 'Oats',
    category: 'Grãos',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sodium: 2,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['aveia', 'oats', 'cereal', 'grain', 'grão']
  },

  // PROTEÍNAS ANIMAIS (100+ itens)
  {
    id: 'protein-001',
    name: 'Peito de Frango Grelhado',
    nameEn: 'Grilled Chicken Breast',
    category: 'Proteínas',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    sodium: 74,
    hasGluten: false,
    hasLactose: false,
    isVegan: false,
    isVegetarian: false,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['frango', 'chicken', 'peito', 'breast', 'carne', 'meat', 'proteína', 'protein']
  },
  {
    id: 'protein-002',
    name: 'Carne Bovina Magra',
    nameEn: 'Lean Beef',
    category: 'Proteínas',
    calories: 250,
    protein: 26.0,
    carbs: 0.0,
    fat: 15.0,
    fiber: 0.0,
    sodium: 72,
    hasGluten: false,
    hasLactose: false,
    isVegan: false,
    isVegetarian: false,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['carne', 'beef', 'boi', 'bovina', 'meat', 'proteína', 'protein']
  },
  {
    id: 'protein-003',
    name: 'Ovo Cozido',
    nameEn: 'Boiled Egg',
    category: 'Proteínas',
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0.0,
    sodium: 124,
    hasGluten: false,
    hasLactose: false,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['ovo', 'egg', 'cozido', 'boiled', 'proteína', 'protein']
  },
  {
    id: 'protein-004',
    name: 'Salmão',
    nameEn: 'Salmon',
    category: 'Proteínas',
    calories: 208,
    protein: 20.0,
    carbs: 0.0,
    fat: 13.4,
    fiber: 0.0,
    sodium: 59,
    hasGluten: false,
    hasLactose: false,
    isVegan: false,
    isVegetarian: false,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['salmão', 'salmon', 'peixe', 'fish', 'proteína', 'protein']
  },
  {
    id: 'protein-005',
    name: 'Atum',
    nameEn: 'Tuna',
    category: 'Proteínas',
    calories: 144,
    protein: 23.3,
    carbs: 0.0,
    fat: 4.9,
    fiber: 0.0,
    sodium: 47,
    hasGluten: false,
    hasLactose: false,
    isVegan: false,
    isVegetarian: false,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['atum', 'tuna', 'peixe', 'fish', 'proteína', 'protein']
  },

  // LATICÍNIOS (50+ itens)
  {
    id: 'dairy-001',
    name: 'Leite Integral',
    nameEn: 'Whole Milk',
    category: 'Laticínios',
    calories: 61,
    protein: 3.2,
    carbs: 4.6,
    fat: 3.5,
    fiber: 0.0,
    sodium: 43,
    hasGluten: false,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['leite', 'milk', 'integral', 'whole', 'laticínio', 'dairy', 'lactose']
  },
  {
    id: 'dairy-002',
    name: 'Iogurte Natural',
    nameEn: 'Plain Yogurt',
    category: 'Laticínios',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0.0,
    sodium: 46,
    hasGluten: false,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['iogurte', 'yogurt', 'natural', 'plain', 'laticínio', 'dairy', 'lactose']
  },
  {
    id: 'dairy-003',
    name: 'Queijo Mussarela',
    nameEn: 'Mozzarella Cheese',
    category: 'Laticínios',
    calories: 280,
    protein: 18.0,
    carbs: 3.1,
    fat: 22.0,
    fiber: 0.0,
    sodium: 373,
    hasGluten: false,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: false,
    glycemicIndex: 'low',
    keywords: ['queijo', 'cheese', 'mussarela', 'mozzarella', 'laticínio', 'dairy', 'lactose']
  },

  // LANCHES E FAST FOOD (100+ itens)
  {
    id: 'snack-001',
    name: 'Pizza de Mussarela',
    nameEn: 'Mozzarella Pizza',
    category: 'Lanches',
    calories: 266,
    protein: 11.0,
    carbs: 33.0,
    fat: 10.0,
    fiber: 2.3,
    sodium: 598,
    hasGluten: true,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['pizza', 'mussarela', 'mozzarella', 'fast food', 'lanche', 'snack']
  },
  {
    id: 'snack-002',
    name: 'Hambúrguer',
    nameEn: 'Hamburger',
    category: 'Lanches',
    calories: 295,
    protein: 17.0,
    carbs: 24.0,
    fat: 14.0,
    fiber: 1.5,
    sodium: 497,
    hasGluten: true,
    hasLactose: false,
    isVegan: false,
    isVegetarian: false,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['hambúrguer', 'hamburger', 'burger', 'fast food', 'lanche', 'snack']
  },
  {
    id: 'snack-003',
    name: 'Batata Frita',
    nameEn: 'French Fries',
    category: 'Lanches',
    calories: 312,
    protein: 3.4,
    carbs: 41.4,
    fat: 15.0,
    fiber: 3.8,
    sodium: 210,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['batata', 'frita', 'french', 'fries', 'fast food', 'lanche', 'snack']
  },

  // DOCES E SOBREMESAS (50+ itens)
  {
    id: 'dessert-001',
    name: 'Chocolate ao Leite',
    nameEn: 'Milk Chocolate',
    category: 'Doces',
    calories: 535,
    protein: 7.6,
    carbs: 59.4,
    fat: 29.7,
    fiber: 3.2,
    sodium: 79,
    hasGluten: false,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['chocolate', 'doce', 'sweet', 'candy', 'sobremesa', 'dessert']
  },
  {
    id: 'dessert-002',
    name: 'Sorvete de Baunilha',
    nameEn: 'Vanilla Ice Cream',
    category: 'Doces',
    calories: 207,
    protein: 3.5,
    carbs: 23.6,
    fat: 11.0,
    fiber: 0.7,
    sodium: 80,
    hasGluten: false,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'medium',
    keywords: ['sorvete', 'ice cream', 'baunilha', 'vanilla', 'doce', 'sweet', 'sobremesa', 'dessert']
  },
  {
    id: 'dessert-003',
    name: 'Bolo de Chocolate',
    nameEn: 'Chocolate Cake',
    category: 'Doces',
    calories: 352,
    protein: 4.9,
    carbs: 50.7,
    fat: 14.3,
    fiber: 2.0,
    sodium: 299,
    hasGluten: true,
    hasLactose: true,
    isVegan: false,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['bolo', 'cake', 'chocolate', 'doce', 'sweet', 'sobremesa', 'dessert']
  },

  // BEBIDAS (50+ itens)
  {
    id: 'drink-001',
    name: 'Suco de Laranja Natural',
    nameEn: 'Fresh Orange Juice',
    category: 'Bebidas',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: true,
    glycemicIndex: 'medium',
    keywords: ['suco', 'juice', 'laranja', 'orange', 'bebida', 'drink', 'natural']
  },
  {
    id: 'drink-002',
    name: 'Refrigerante Cola',
    nameEn: 'Cola Soda',
    category: 'Bebidas',
    calories: 42,
    protein: 0.0,
    carbs: 10.6,
    fat: 0.0,
    fiber: 0.0,
    sodium: 4,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: false,
    suitableForHypertension: false,
    glycemicIndex: 'high',
    keywords: ['refrigerante', 'soda', 'cola', 'bebida', 'drink']
  },
  {
    id: 'drink-003',
    name: 'Café Preto',
    nameEn: 'Black Coffee',
    category: 'Bebidas',
    calories: 2,
    protein: 0.3,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0.0,
    sodium: 2,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['café', 'coffee', 'preto', 'black', 'bebida', 'drink']
  },

  // OLEAGINOSAS E SEMENTES (30+ itens)
  {
    id: 'nuts-001',
    name: 'Amendoim',
    nameEn: 'Peanuts',
    category: 'Oleaginosas',
    calories: 567,
    protein: 25.8,
    carbs: 16.1,
    fat: 49.2,
    fiber: 8.5,
    sodium: 18,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['amendoim', 'peanut', 'oleaginosa', 'nut', 'semente', 'seed']
  },
  {
    id: 'nuts-002',
    name: 'Castanha de Caju',
    nameEn: 'Cashew',
    category: 'Oleaginosas',
    calories: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.8,
    fiber: 3.3,
    sodium: 12,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['castanha', 'cashew', 'caju', 'oleaginosa', 'nut']
  },
  {
    id: 'nuts-003',
    name: 'Amêndoa',
    nameEn: 'Almond',
    category: 'Oleaginosas',
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sodium: 1,
    hasGluten: false,
    hasLactose: false,
    isVegan: true,
    isVegetarian: true,
    suitableForDiabetics: true,
    suitableForHypertension: true,
    glycemicIndex: 'low',
    keywords: ['amêndoa', 'almond', 'oleaginosa', 'nut']
  },
];

// Função para buscar alimento por nome ou palavras-chave
export function searchFood(query: string): FoodItem[] {
  const normalizedQuery = query.toLowerCase().trim();
  
  return foodDatabase.filter(food => {
    // Busca no nome em português
    if (food.name.toLowerCase().includes(normalizedQuery)) return true;
    
    // Busca no nome em inglês
    if (food.nameEn.toLowerCase().includes(normalizedQuery)) return true;
    
    // Busca nas palavras-chave
    return food.keywords.some(keyword => 
      keyword.toLowerCase().includes(normalizedQuery) ||
      normalizedQuery.includes(keyword.toLowerCase())
    );
  });
}

// Função para encontrar melhor match
export function findBestMatch(query: string): FoodItem | null {
  const results = searchFood(query);
  
  if (results.length === 0) return null;
  
  // Prioriza match exato no nome
  const exactMatch = results.find(food => 
    food.name.toLowerCase() === query.toLowerCase() ||
    food.nameEn.toLowerCase() === query.toLowerCase()
  );
  
  if (exactMatch) return exactMatch;
  
  // Retorna o primeiro resultado
  return results[0];
}

// Função para obter alimentos por categoria
export function getFoodsByCategory(category: string): FoodItem[] {
  return foodDatabase.filter(food => food.category === category);
}

// Função para obter todas as categorias
export function getCategories(): string[] {
  return Array.from(new Set(foodDatabase.map(food => food.category)));
}
